name: Build/Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        otp_version: [25, 24]
        rebar3_version: ["3.20"]
        os: ["ubuntu-latest"]
        include:
          - otp_version: 23
            rebar3_version: "3.20"
            os: "ubuntu-20.04"
          - otp_version: 22
            rebar3_version: "3.16"
            os: "ubuntu-20.04"
          - otp_version: 21
            rebar3_version: "3.15"
            os: "ubuntu-20.04"
          - otp_version: 20
            rebar3_version: "3.15"
            os: "ubuntu-20.04"
      fail-fast: false
      max-parallel: 2

    runs-on: ["${{ matrix.os }}"]

    name: "OTP${{ matrix.otp_version}}, rebar3 v${{ matrix.rebar3_version }}"

    steps:
    - uses: actions/checkout@v3
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        install-rebar: true
        install-hex: true
        rebar3-version: ${{ matrix.rebar3_version }}

    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 eunit
